--CONSULTAR VIDEOS CON ERRORES

select TEMA.NOMBRE AS TEMA ,TEMPORAL.URL AS URL, COUNT(OPINION.NUMERO) AS numeroOpiniones, COUNT(OPINION.NUMERO)
from TEMA ,TEMPORAL,CONTENIDOTEMA,OPINION
WHERE TEMA.NOMBRE = CONTENIDOTEMA.TEMA AND  TEMPORAL.NOMBRE = CONTENIDOTEMA.CONTENIDO AND TEMPORAL.NOMBRE = OPINION.CONTENIDOID AND OPINION.DETALLE = 'momentos de error' AND  TEMPORAL.TIPO ='V'
GROUP BY TEMA.NOMBRE, TEMPORAL.URL,OPINION.NUMERO;

--consultar los diez mas populares del mes 

select perfil, nombre , url
from temporal;