CREATE OR REPLACE PACKAGE PC_OPINIONES IS 
	PROCEDURE AD_OPINION (xtipo IN VARCHAR, xjustificacion IN VARCHAR, xdetalle IN VARCHAR, xperfilc IN VARCHAR, xcontenidoid IN VARCHAR);
    PROCEDURE EL_OPINION (xnumero IN NUMBER);
END PC_OPINIONES;


