CREATE OR REPLACE TRIGGER AUTO_VALORACION
    BEFORE INSERT ON VALORACION
    FOR EACH ROW
DECLARE 
    NUM NUMBER;
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM VALORACION;
    :NEW.ID := NUM;
END;
/

CREATE OR REPLACE TRIGGER AUTO_UBICACION
    BEFORE INSERT ON UBICACION
    FOR EACH ROW
DECLARE 
    NUM NUMBER;    
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM UBICACION;
    :NEW.ID := NUM;
END;
/

CREATE OR REPLACE TRIGGER AUTO_RECLAMO
    BEFORE INSERT ON RECLAMO
    FOR EACH ROW
DECLARE 
    NUM NUMBER;   
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM RECLAMO;
    :NEW.ID := NUM;
END;
/

CREATE OR REPLACE TRIGGER AUTO_CONDUCTOR
    BEFORE INSERT ON CONDUCTOR
    FOR EACH ROW
DECLARE 
    NUM NUMBER;  
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM CONDUCTOR;
    :NEW.ID := NUM;
END;
/
CREATE OR REPLACE TRIGGER AUTO_POLIZA
    BEFORE INSERT ON POLIZA
    FOR EACH ROW
DECLARE 
    NUM NUMBER;  
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM POLIZA;
    :NEW.ID := NUM;
END;
/

CREATE OR REPLACE TRIGGER AUTO_REGISTRO
    BEFORE INSERT ON REGISTRO
    FOR EACH ROW
DECLARE 
    NUM NUMBER;
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM REGISTRO;
    :NEW.RNUMERO := NUM;
END;
/
CREATE OR REPLACE TRIGGER AUTO_PUNTOATENCION
    BEFORE INSERT ON PUNTOATENCION
    FOR EACH ROW
DECLARE 
    NUM NUMBER;
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM PUNTOATENCION;
    :NEW.ID := NUM;
END;
/

CREATE OR REPLACE TRIGGER AUTO_PROYECTO
    BEFORE INSERT ON PROYECTO
    FOR EACH ROW
DECLARE 
    NUM NUMBER;
    AUX_FECHA  DATE;
BEGIN
    NUM:=1;
    AUX_FECHA := TO_DATE(SYSDATE,'YYYY-MM-DD');
    SELECT COUNT(*)+1 INTO NUM FROM PROYECTO;
    :NEW.FECHAINICIO := AUX_FECHA;
    :NEW.ID := NUM;
END;
/
CREATE OR REPLACE TRIGGER AUTO_ADMINISTRADOR
    BEFORE INSERT ON ADMINISTRADOR
    FOR EACH ROW
DECLARE 
    NUM NUMBER;
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM ADMINISTRADOR;
    :NEW.ID := NUM;
END;
/
CREATE OR REPLACE TRIGGER AUTO_VENDEDOR
    BEFORE INSERT ON VENDEDOR
    FOR EACH ROW
DECLARE 
    NUM NUMBER;
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM VENDEDOR;
    :NEW.ID := NUM;
END;
/
CREATE OR REPLACE TRIGGER AUTO_COBERTURA
    BEFORE INSERT ON COBERTURA
    FOR EACH ROW
DECLARE 
    NUM NUMBER;
BEGIN
    NUM:=1;
    SELECT COUNT(*)+1 INTO NUM FROM COBERTURA;
    :NEW.ID := NUM;
END;
/

