ALTER TABLE VALORACION ADD CONSTRAINT FK_CONSULTA_VALORACION FOREIGN KEY (VEHICULO) 
REFERENCES VEHICULO(VIN);

ALTER TABLE VEHICULO ADD CONSTRAINT FK_CONSULTA_VEHICULO FOREIGN KEY (MARCA) 
REFERENCES MARCA(NOMBRE);

ALTER TABLE VEHICULO ADD CONSTRAINT FK_CONSULTA_VEHICULOC FOREIGN KEY (CONDUCTOR) 
REFERENCES CONDUCTOR(ID);

--ALTER TABLE RECLAMO ADD CONSTRAINT FK_CONSULTA_RECLAMO FOREIGN KEY (UBICACION) 
--REFERENCES AAA(AAA);

ALTER TABLE RECLAMO ADD CONSTRAINT FK_CONSULTA_RECLAMOV FOREIGN KEY (VEHICULO) 
REFERENCES VEHICULO(VIN);

ALTER TABLE RECLAMO ADD CONSTRAINT FK_CONSULTA_RECLAMOR FOREIGN KEY (REGISTRO) 
REFERENCES REGISTRO(RNUMERO);

ALTER TABLE RECLAMO ADD CONSTRAINT FK_CONSULTA_RECLAMOC FOREIGN KEY (CONDUCTOR) 
REFERENCES CONDUCTOR(ID);

ALTER TABLE RECLAMO ADD CONSTRAINT FK_CONSULTA_RECLAMOP FOREIGN KEY (POLIZA) 
REFERENCES POLIZA(ID);

ALTER TABLE RECLAMO ADD CONSTRAINT FK_CONSULTA_RECLAMOE FOREIGN KEY (ADMINISTRADOR) 
REFERENCES ADMINISTRADOR(ID);