ALTER TABLE VALORACION ADD CONSTRAINT PK_VALORACION  PRIMARY KEY (ID);

ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO  PRIMARY KEY (VIN);

ALTER TABLE MARCA ADD CONSTRAINT PK_MARCA  PRIMARY KEY (NOMBRE);

ALTER TABLE UBICACION ADD CONSTRAINT PK_UBICACION  PRIMARY KEY (LATITUD,LONGITUD);

ALTER TABLE RECLAMO ADD CONSTRAINT PK_RECLAMO  PRIMARY KEY (ID);

ALTER TABLE CONDUCTOR ADD CONSTRAINT PK_CONDUCTOR  PRIMARY KEY (ID);

ALTER TABLE POLIZA ADD CONSTRAINT PK_POLIZA  PRIMARY KEY (ID);

ALTER TABLE REGISTRO ADD CONSTRAINT PK_REGISTRO  PRIMARY KEY (RNUMERO);

ALTER TABLE PUNTOATENCION ADD CONSTRAINT PK_PUNTOATENCION  PRIMARY KEY (ID);

ALTER TABLE PROYECTO ADD CONSTRAINT PK_PROYECTO  PRIMARY KEY (ID);

ALTER TABLE ADMINISTRADOR ADD CONSTRAINT PK_ADMINISTRADOR  PRIMARY KEY (ID);

ALTER TABLE VENDEDOR ADD CONSTRAINT PK_VENDEDOR  PRIMARY KEY (ID);

ALTER TABLE COVERTURA ADD CONSTRAINT PK_COVERTURA  PRIMARY KEY (ID);