--CREAR TABLAS 
CREATE TABLE CONDUCTOR (
    IDENTIFICACION VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(64) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL,    
    TELEFONO NUMBER(10),
    EDAD NUMBER(2) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL
);

CREATE TABLE VALORACION(
    PRECIO NUMBER(10,2) NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR2(10) NOT NULL
);


CREATE TABLE VEHICULO (
    VIN VARCHAR2(15) NOT NULL,
    FECHA DATE NOT NULL,
    MODELO VARCHAR2(10) NOT NULL,
    COLOR VARCHAR2(8) NOT NULL,
    TIPO VARCHAR2(10) NOT NULL
);


CREATE TABLE RECLAMO (
    ID NUMBER(5) NOT NULL,
    FECHA DATE NOT NULL,
    DETALLE VARCHAR2(100)NOT NULL,
    VALOR NUMBER(10,2) NOT NULL
);


CREATE TABLE UBICACION(
    LONGITUD NUMBER(2,10) NOT NULL,
    LATITUD NUMBER(2,10) NOT NULL,
    CIUDAD VARCHAR2(20) NOT NULL,
    PAIS VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL
);

CREATE TABLE PUNTOATENCION
(
    ID NUMBER(3) NOT NULL,
    CIUDAD VARCHAR2(20) NOT NULL
);

CREATE TABLE MARCA(
    SIGLA VARCHAR2(5) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL
);

CREATE TABLE POLIZA(
    DEDUCIBLE NUMBER(10,2) NOT NULL
);

CREATE TABLE REGISTRO(
    RNUMERO NUMBER(5) NOT NULL
);

CREATE TABLE ADMINISTRADOR(
    ID NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    TELEFONO NUMBER(10) NOT NULL,
    CORREO VARCHAR2(50) NOT NULL
);

CREATE TABLE VENDEDOR(
    ID NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    SALARIO NUMBER(10,2) NOT NULL,
    CORREO VARCHAR2(50) NOT NULL,
    FECHAENTRADA DATE NOT NULL
);


CREATE TABLE PROYECTO(
   ID NUMBER(5) NOT NULL,
   NOMBRE VARCHAR2(20) NOT NULL,
   FECHAINICION DATE NOT NULL,
   FECHAFIN DATE NOT NULL
);
