--CREAR TABLAS 
CREATE TABLE CONDUCTOR(
    ID VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(64) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL,    
    TELEFONO NUMBER(10),
    EDAD NUMBER(2) NOT NULL,
    CIUDAD VARCHAR(20) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    REGISTRO NUMBER(10) NOT NULL
);


CREATE TABLE VALORACION(
    PRECIO NUMBER(10,2) NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR2(10) NOT NULL,
    vehiculo VARCHAR(15) NOT NULL
);


CREATE TABLE VEHICULO (
    VIN VARCHAR2(15) NOT NULL,
    FECHA DATE NOT NULL,
    MODELO NUMBER(4) NOT NULL,
    COLOR VARCHAR2(8) NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,
    MARCA VARCHAR(5) NOT NULL
);


CREATE TABLE RECLAMO (
    ID NUMBER(10) NOT NULL,
    FECHA DATE NOT NULL,
    DETALLE VARCHAR2(100)NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    POLIZA NUMBER(10)NOT NULL,
    VEHICULO VARCHAR(15),
    CONDUCTOR NUMBER(10),
    PATENCION NUMBER(10)
);


CREATE TABLE UBICACION(
    LONGITUD NUMBER(2,10) NOT NULL,
    LATITUD NUMBER(2,10) NOT NULL,
    CIUDAD VARCHAR2(20) NOT NULL,
    PAIS VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR2(20) 
);

CREATE TABLE PUNTOATENCION
(
    ID NUMBER(10) NOT NULL
);

CREATE TABLE MARCA(
    SIGLA VARCHAR2(5) NOT NULL,
    NOMBRE VARCHAR2(32) NOT NULL
);  

CREATE TABLE POLIZA(
    ID NUMBER(10) NOT NULL,
    DEDUCIBLE NUMBER(10,2) NOT NULL
);


CREATE TABLE ADMINISTRADOR(
    ID NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    TELEFONO NUMBER(10) NOT NULL,
    CORREO VARCHAR2(30) NOT NULL
);

CREATE TABLE VENDEDOR(
    ID NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(32) NOT NULL,
    SALARIO NUMBER(10,2) NOT NULL,
    CORREO VARCHAR2(30) NOT NULL,
    FECHAENTRADA DATE NOT NULL
);


CREATE TABLE PROYECTO(
   ID NUMBER(10) NOT NULL,
   NOMBRE VARCHAR2(20) NOT NULL,
   FECHAINICION DATE NOT NULL,
   FECHAFIN DATE NOT NULL
);
